#!/usr/bin/env node
/**
 * Upload files from gallery-upload/ to Vercel Blob and regenerate src/data/gallery.ts
 *
 * Setup:
 * 1. Create a Blob store at vercel.com → Storage → Blob
 * 2. Copy BLOB_READ_WRITE_TOKEN to .env (see .env.example)
 * 3. Drop photos/videos into gallery-upload/
 * 4. Run: npm run gallery:upload
 */

import { put } from "@vercel/blob";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, extname, basename } from "node:path";

const UPLOAD_DIR = "gallery-upload";
const OUTPUT_FILE = "src/data/gallery.ts";

const IMAGE_EXT = new Set([".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif"]);
const VIDEO_EXT = new Set([".mp4", ".webm", ".mov"]);

const token = process.env.BLOB_READ_WRITE_TOKEN;
if (!token) {
  console.error("Missing BLOB_READ_WRITE_TOKEN. Add it to .env (see .env.example).");
  process.exit(1);
}

function altFromFilename(filename) {
  return basename(filename, extname(filename))
    .replace(/[-_]+/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

const files = (await readdir(UPLOAD_DIR)).filter((f) => !f.startsWith("."));
if (files.length === 0) {
  console.error(`No files found in ${UPLOAD_DIR}/`);
  process.exit(1);
}

/** @type {Array<{ id: string; type: string; src: string; alt: string; poster?: string }>} */
const items = [];

for (const file of files.sort()) {
  const ext = extname(file).toLowerCase();
  const isVideo = VIDEO_EXT.has(ext);
  const isImage = IMAGE_EXT.has(ext);

  if (!isVideo && !isImage) {
    console.warn(`Skipping unsupported file: ${file}`);
    continue;
  }

  const body = await readFile(join(UPLOAD_DIR, file));
  const blob = await put(`gallery/${file}`, body, {
    access: "public",
    token,
    addRandomSuffix: false,
  });

  const item = {
    id: basename(file, ext).toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    type: isVideo ? "video" : "image",
    src: blob.url,
    alt: altFromFilename(file),
  };

  items.push(item);
  console.log(`Uploaded ${file} → ${blob.url}`);
}

const tsItems = items
  .map((item) => {
    if (item.type === "video") {
      return `  {
    id: ${JSON.stringify(item.id)},
    type: "video",
    src: ${JSON.stringify(item.src)},
    alt: ${JSON.stringify(item.alt)},
  }`;
    }
    return `  {
    id: ${JSON.stringify(item.id)},
    type: "image",
    src: ${JSON.stringify(item.src)},
    alt: ${JSON.stringify(item.alt)},
  }`;
  })
  .join(",\n");

const finalContent = `export type GalleryImage = {
  id: string;
  type: "image";
  src: string;
  alt: string;
};

export type GalleryVideo = {
  id: string;
  type: "video";
  src: string;
  alt: string;
  poster?: string;
};

export type GalleryItem = GalleryImage | GalleryVideo;

/** Auto-generated by npm run gallery:upload — do not edit manually. */
export const galleryItems: GalleryItem[] = [
${tsItems}
];
`;

await writeFile(OUTPUT_FILE, finalContent);
console.log(`\nWrote ${items.length} items to ${OUTPUT_FILE}`);
